model_list:
  - model_name: "gpt-oss:20b"
    litellm_params:
      model: "ollama/gpt-oss:20b"
      api_base: "http://host.docker.internal:11434"
      timeout: 120

litellm_settings:
  drop_params: ["logprobs"]

general_settings:
  telemetry: False
